name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_call:
    outputs:
      gitversion:
        description: The output of GitVersion
        value: ${{ jobs.build.outputs.gitversion }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      gitversion: ${{ toJSON(steps.gitversion.outputs) }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.0.0
      with:
        versionSpec: '6.x'

    - name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v4.0.0
      id: gitversion

    - name: Use GitVersion to update project
      uses: gittools/actions/gitversion/command@v4.0.0
      with:
        arguments: '/updateprojectfiles'

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: SpectatorDisabler/bin/Release/net48/SpectatorDisabler-${{ steps.gitversion.outputs.AssemblySemVer }}.dll
        if-no-files-found: error
