name: CI and Release

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'

    - name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v1.1.1
      id: gitversion
      with:
        additionalArguments: '/updateprojectfiles'

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: Spectator-Disabler/bin/Release/net48/SpectatorDisabler-${{ steps.gitversion.outputs.assemblySemVer }}.dll
        if-no-files-found: error

  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
          versionSpec: '5.x'

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: artifact

    - name: Format release message
      run: |
        echo '${{ github.event.head_commit.message }}' | tail -n +2 > release-message.txt
        cat release-message.txt

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.gitversion.outputs.majorMinorPatch }}
        name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
        body_path: release-message.txt
        files: SpectatorDisabler-${{ steps.gitversion.outputs.assemblySemVer }}.dll
